remote_theme: pages-themes/slate@v0.2.0
show_downloads: false
title: UStep
description: For Academic Excellence
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
